Bar chart
GeorgiaTech-DDI/makerspace_dashboard pull request #12
Opened 2024-09-27 05:12 UTC by thinhnpctnguyen

Bar chart for average print time

2024-10-01 17:42 UTC, cgensheimer commented
try to merge main branch into this. also remove the big number for each month (as ojas pointed out its a sum of averages which is basically useless) or make it a true average of all the averages

2024-10-01 17:42 UTC, cgensheimer requested changes
Good work, just those changes

2024-10-03 21:57 UTC, thinhnpctnguyen commented
merged main. and changed the function to calculate the true average.

2024-10-10 03:45 UTC, cgensheimer approved these changes

2024-10-10 03:45 UTC, merged